** TODO 

send this to useR-2014@R-project.org before January 10, 2016.

** Tutorial Title

Interactive, animated, multi-layer graphics

I wonder if we should specifically mention animint in the title, since
Ramnath is submitting another tutorial on htmlwidgets?

** Instructors

| Name                | Institution      | Address             | Email                       |
|---------------------+------------------+---------------------+-----------------------------|
| Toby Dylan Hocking  | McGill           | Montreal, Canada    | toby.hocking@mail.mcgill.ca |
| Claus Thorn Ekstrøm | Univ. Copenhagen | Copenhagen, Denmark | ekstrom@sund.ku.dk          |

** Short Instructor Biography

Toby Dylan Hocking is the original author of the animint package
(https://github.com/tdhock/animint), which was presented in an invited
session at Joint Statistical Meetings 2015.

https://www.amstat.org/meetings/jsm/2015/onlineprogram/AbstractDetails.cfm?abstractid=314184

_The bio should enable the scientific committee to gauge the
instructor's qualifications for the tutorial. Links to works previous
tutorials and/or relevant publications may be included._

** Brief Description of Tutorial

The animint package simplifies creation of interactive, animated,
multi-layer graphics. In this tutorial we will explain how to use R
packages with similar functionality (ggvis, shiny, animation,
ggplot2), and explain the relative strengths and weaknesses of each
package.

** Goals

1. By showing several examples, explain what it means for a
   statistical graphic to be "interactive," "animated," and
   "multi-layer."
2. Explain how existing R packages can be used to create these
   graphics.
3. Explain the strengths and weaknesses of the existing R packages, to
   highlight directions for future work.

** Detailed Outline

_Detailed outline text._

** Justification

_Justification why tutorial is current and important._

** Background Knowledge

Since we plan to present state-of-the-art interactive graphics, people
should know how to use R data structures (lists, data.frames) and the
ggplot2 package. 

Even though many examples will be interactive web graphics, we will
assume only knowledge of R, not HTML/JavaScript.

There are two classes of potential attendees:
- UseRs who are not very familiar with interactive graphics should
  benefit the most, since we will give a high-level overview of many
  different packages.
- DevelopeRs of interactive packages are encouraged to come, to
  discuss the current state-of-the-art and future directions.

** Expected Number of Attendees

_How many do you expect to attend the tutorial?_


