The official description from useR is
http://user2016.org/tutorials/13.html

- Part 1: [[http://tdhock.github.io/interactive-tutorial/IntGraph.html][Claus Thorn Ekstrom's slides]], [[https://github.com/tdhock/interactive-tutorial/blob/gh-pages/IntGraph.Rmd][source]].
- Part 2: Toby Dylan Hocking, animation and direct manipulation.
  - [[file:HOCKING-handout.pdf][1-page summary handout]], [[file:HOCKING-handout.tex][source]].
  - Please install required packages via
    =source("http://tdhock.github.io/interactive-tutorial/packages.R")=
    and if that worked then =example(animint)= should open some web
    browser windows containing animints.
  - Thanks to [[https://github.com/hadley][Hadley Wickham]], the ggplot2 dev team, and my animint
    GSOC 2013-2016 students [[https://github.com/srvanderplas][Susan VanderPlas]], [[https://github.com/cpsievert][Carson Sievert]], [[https://github.com/caijun][Tony
    Tsai]], [[https://github.com/kferris10][Kevin Ferris]], [[https://github.com/faizan-khan-iit][Faizan Khan]]. Without their work none of this
    would be possible!
  - [[http://cbio.ensmp.fr/~thocking/interactive-tutorial/introduction-vocabulary.html][Introduction and vocabulary]] (5 min), [[https://github.com/tdhock/interactive-tutorial/blob/gh-pages/introduction-vocabulary.Rmd][source]].
  - [[http://cbio.ensmp.fr/~thocking/animint-book/Ch02-ggplot2.html][Basics of ggplot2 and animint]] (25 min).
  - [[http://cbio.ensmp.fr/~thocking/animint-book/Ch03-showSelected.html][aes(showSelected)]] (25 min).
  - [[http://cbio.ensmp.fr/~thocking/animint-book/Ch04-clickSelects.html][aes(clickSelects)]] (25 min).
  - [[file:HOCKING-exercises.R][Exercises]] ([[file:HOCKING-solutions.R][solutions]]).

** SHERC RIC workshop Spring 2022

Title: Animated, Interactive Data Visualization: animint2 R package

Abstract: Data visualization is useful for understanding patterns in large data sets and models. 
In constrast with static data visualization which produces a single image rendered as a PDF/PNG/etc image file, interactive data visualization can show many images of a data set, by rendering to a web page which can be clicked in order to show/hide different details of the data set.
Interactive data visualization is useful for exploratory data analysis, for research, and for teaching.
This tutorial will explain how to create animated and interactive data visualizations using the animint2 R package.
It will cover chapters 2-4 of the animint2 Manual, https://rcdata.nau.edu/genomic-ml/animint2-manual/Ch02-ggplot2.html
Participants in this workshop should have R installed on their computer so they can follow along with the exercises.
Some prior knowledge of R and the ggplot2 package would be useful.
We will begin by explaining the basics of ggplots (grammar of graphics plots), including plot sketching, geoms, and aesthetic mappings from data variables to visual properties.
Next we will show how the animint() function can be used to render a list of ggplots on a web page.
Finally we will explain the showSelected and clickSelected keywords, which can be used to add interactivity to ggplots.
At the end of this workshop, participants should understand the basics of static and interactive data visualization using the grammar of graphics.
- [[https://github.com/tdhock/animint/wiki/Gallery][Animint Gallery containing links to example data visualizations and source code]].
- [[http://ml.nau.edu/viz/2022-02-02-gradient-descent-regression/][Gradient descent for linear regression]].
- [[https://bl.ocks.org/tdhock/raw/8d188b04ca9aa629a3700a8055bf27dd/][Evaluation of binary classification algorithms, highly imbalanced Table Mountain Pine data]]
