** TODO 

send this to useR-2014@R-project.org before January 10, 2016.

CE (General comment)

What I had in mind for the course/tutorial when we talked about the
tutorial last year was a general introduction
to the existing possibilities to create interactive/dynamic graphics
in R. The tutorial would be a hodge-podge of different packages and
should have two main goals: give the audience an overview of the
current possibilities in R as well as presenting the advantages/disadvantages of the
different approaches. A person attending the tutorial should have an
idea about the possibilities and "where to start" without being an
expert on any particular package.

I think I get the same vibe when reading your draft tutorial - is
that correct?

Also, since we know that Ramnath is working on an htmlwidgets
tutorial, I think it would even more important for this tutorial to
focus on presenting as many different approaches as possible.


** Tutorial Title

Interactive, animated, multi-layer graphics

I wonder if we should specifically mention animint in the title, since
Ramnath is submitting another tutorial on htmlwidgets?

CE: I think it would be crucial for the title to make sure it
differentiates itself from the other possible tutorial. Maybe we
should hone in on the title as we get more details on the contents? 


** Instructors

| Name                | Institution      | Address             | Email                       |
|---------------------+------------------+---------------------+-----------------------------|
| Toby Dylan Hocking  | McGill           | Montreal, Canada    | toby.hocking@mail.mcgill.ca |
| Claus Thorn Ekstrøm | Univ. Copenhagen | Copenhagen, Denmark | ekstrom@sund.ku.dk          |

** Short Instructor Biography

Toby Dylan Hocking is the original author of the animint package
(https://github.com/tdhock/animint), which was presented in an invited
session at Joint Statistical Meetings 2015.

https://www.amstat.org/meetings/jsm/2015/onlineprogram/AbstractDetails.cfm?abstractid=314184


Claus Thorn Ekstrøm is the creator and contributor to a number of R
packages (MESS, MethComp, SuperRanker) and is the author of "The R
Primer" book. He has previously given tutorials on Dynamic
graphics in R and the role of interactive graphics in teaching.

http://biostatistics.dk/presentations/DynGraph.html



** Brief Description of Tutorial

The animint package simplifies creation of interactive, animated,
multi-layer graphics. In this tutorial we will explain how to use R
packages with similar functionality (ggvis, shiny, animation,
ggplot2), and explain the relative strengths and weaknesses of each
package.

** Goals

1. By showing several examples, explain what it means for a
   statistical graphic to be "interactive," "animated," and
   "multi-layer."
2. Explain how existing R packages can be used to create these
   graphics.
3. Explain the strengths and weaknesses of the existing R packages, to
   highlight directions for future work.

** Detailed Outline

_Detailed outline text._

** Justification

_Justification why tutorial is current and important._

** Background Knowledge

Since we plan to present state-of-the-art interactive graphics, people
should know how to use R data structures (lists, data.frames) and the
ggplot2 package. 

Even though many examples will be interactive web graphics, we will
assume only knowledge of R, not HTML/JavaScript.

There are two classes of potential attendees:
- UseRs who are not very familiar with interactive graphics should
  benefit the most, since we will give a high-level overview of many
  different packages.
- DevelopeRs of interactive packages are encouraged to come, to
  discuss the current state-of-the-art and future directions.

** Expected Number of Attendees

_How many do you expect to attend the tutorial?_


