** TODO 

send this to useR-2014@R-project.org before January 10, 2016.

CE (General comment)

What I had in mind for the course/tutorial when we talked about the
tutorial last year was a general introduction
to the existing possibilities to create interactive/dynamic graphics
in R. The tutorial would be a hodge-podge of different packages and
should have two main goals: give the audience an overview of the
current possibilities in R as well as presenting the advantages/disadvantages of the
different approaches. A person attending the tutorial should have an
idea about the possibilities and "where to start" without being an
expert on any particular package.

I think I get the same vibe when reading your draft tutorial - is
that correct?

Also, since we know that Ramnath is working on an htmlwidgets
tutorial, I think it would even more important for this tutorial to
focus on presenting as many different approaches as possible.


** Tutorial Title

Interactive, animated, multi-layer graphics

I wonder if we should specifically mention animint in the title, since
Ramnath is submitting another tutorial on htmlwidgets?

CE: I think it would be crucial for the title to make sure it
differentiates itself from the other possible tutorial. Maybe we
should hone in on the title as we get more details on the contents? 


** Instructors

| Name                | Institution      | Address             | Email                       |
|---------------------+------------------+---------------------+-----------------------------|
| Toby Dylan Hocking  | McGill           | Montreal, Canada    | toby.hocking@mail.mcgill.ca |
| Claus Thorn Ekstrøm | Univ. Copenhagen | Copenhagen, Denmark | ekstrom@sund.ku.dk          |

** Short Instructor Biography

Toby Dylan Hocking is the original author of the animint package
(https://github.com/tdhock/animint), which was presented in an invited
session at Joint Statistical Meetings 2015.

https://www.amstat.org/meetings/jsm/2015/onlineprogram/AbstractDetails.cfm?abstractid=314184


Claus Thorn Ekstrøm is the creator and contributor to a number of R
packages (MESS, MethComp, SuperRanker) and is the author of "The R
Primer" book. He has previously given tutorials on Dynamic
graphics in R and the role of interactive graphics in teaching.

http://biostatistics.dk/presentations/DynGraph.html



** Brief Description of Tutorial

Interactive graphics provide a huge potential for exploratory data
analysis, in teaching, and for reporting data analyses since
interactive graphics invites the viewer to become an active partner in
the analysis and allows for immediate feedback on how the data and
results may change when inputs are modified.

Several R packages provide different approaches to interactive
graphics either a stand-alone solutions or by interfacing to external
graphical libraries. In this tutorial we will provide an overview and
introduction to R packages (animint, shiny, rCharts, rMaps, ggvis,
htmlwidgets) that consider different types of interactive graphics.

The animint package simplifies creation of interactive, animated,
multi-layer graphics, and we will will give a thorough comparison of a
number of packages with similar functionality to the animint (ggvis,
shiny, animation, ggplot2), and explain the relative strengths and
weaknesses of each package.


** Goals

1. To explain and emphasize the role that interactive graphics will
   have in reporting, scientific journals, and in teaching.
2. By showing several examples, explain what it means for a
   statistical graphic to be "interactive," "animated," and
   "multi-layer."
3. Explain how existing R packages can be used to create various
   different types of interactive graphics these
   graphics.
4. Explain the strengths and weaknesses of the existing R packages, to
   highlight directions for future work.

** Detailed Outline

The three hours will roughly be structured as follows:

1. Discussion about the role of interactive graphics in exploratory
   data analysis, from a learning and teaching perspective. The
   discussion will showcase possibilities offered by interactive and
   dynamic graphics offered by the rCharts, shiny, rMaps
2. 
3. 



Besides the structure outlined above, we will be discussing 

- the importance
- what it means for a statistical graphic to be "interactive," "animated," and
   "multi-layer."
2. Explain how existing R packages can be used to create these
   graphics.
3. Explain the strengths and weaknesses of the existing R packages, to
   highlight directions for future work.

rCharts, shiny, rMaps, htmlwidgets, plotly, R2D3


** Justification

Interactive graphics provide a huge potential for exploratory data
analysis, in teaching, and for reporting data analyses. Interactive
graphics such as those by the D3 JavScript library invites the viewer
to become an active partner in the analysis and allows for immediate
feedback on how the data and results may change when inputs are
modified.

The role of graphics is expanding and is moving away from simple
static representations found in scientific journals to more
interactive representations where the user is directly involved in
exploring different facets of the data. In that sense, the reader
indirectly takes on the role of the analyst, and R is the ideal tool
to produce integrated, interactive graphics and for interfacing with
some of the external graphics libraries that exist.

The various implementations for interactive graphics found in R
packages are often highly specialized in the same way as high-level
plots, and just a few introduce graphics grammar so they typically
have completely different syntax. This tutorial will give an overview
of the capabilities for creating interactive graphics in R, present
practical examples to produce interactive graphics, and describe the
frustrations and shortcomings from the perspective of users new to
these packages may encounter.

When the tutorial is over the attendees should 1) have an overview of the
packages for producing interactive graphics, 2) have seen and tried
examples so they are able to create interactive graphics using some of
the packages presented, and 3) have seen the broad scope of variation
among packages that seek to produce the same type of graphics.


** Background Knowledge

Since we plan to present state-of-the-art interactive graphics, people
should know how to use R data structures (lists, data.frames) and the
ggplot2 package. 

Even though many examples will be interactive web graphics, we will
assume only knowledge of R, not HTML/JavaScript.

There are two classes of potential attendees:
- UseRs who are not very familiar with interactive graphics should
  benefit the most, since we will give a high-level overview of many
  different packages.
- DevelopeRs of interactive packages are encouraged to come, to
  discuss the current state-of-the-art and future directions.

** Expected Number of Attendees

_How many do you expect to attend the tutorial?_

I have no clue on how to assess this
