Proposal for an tutorial overview of interactive graphics packages

Fill in [[file:tutorial-prop.org][template]] and send it to useR-2014@R-project.org before January
10, 2016.

Below is old materials that we may want to copy to the template.

** Goals, why the tutorial is important

There are two main goals for this tutorial:
- Summarize of the differences and relative strengths of the different
  packages which are now available for making interactive graphics
  using R.
- Bring the developers of these packages together in one place, to
  discuss future directions for interactive graphics in R.

** Detailed outline

*First hour: simple graphics.* generate single-layer, single-panel
interactive web graphics with only 1 line of R code (rCharts,
googleVis). Interactivity is mostly limited to tooltips i.e. a little
popup window that shows more information about a data point when you
move your mouse over it.

*Second hour: brushing.* One or several rows of 1 data.frame can be
brushed interactively using the mouse, and the brushed data are
highlighted in several linked plots (RIGHT, iplots, cranvas).

*Third hour: show/hide data subsets.* Several multi-layer plots show
different columns of a data set, and different rows can be shown over
time (animation) or in response to mouse clicks (interactivity). We
will focus on a detailed description about how to generate [[http://sugiyama-www.cs.titech.ac.jp/~toby/animint/WorldBank/viz.html][this
GapMinder-style multipanel, multilayer, interactive animation]] using
packages animation, animint, and shiny+ggvis.
- 10 minutes: [[https://github.com/tdhock/interactive-tutorial/tree/master/animation][overview of the differences between the animation,
  animint, shiny, and ggvis packages]].
- 15 minutes: animation.
- 15 minutes: animint.
- 15 minutes: shiny+ggvis.
   
** Background knowledge required, potential attendees

Since we plan to present state-of-the-art interactive graphics, people
should know how to use R data structures (lists, data.frames) and the
ggplot2 package. 

Even though many examples will be interactive web graphics, we will
assume only knowledge of R, not HTML/JavaScript.

There are two classes of potential attendees:
- UseRs who are not very familiar with interactive graphics should
  benefit the most, since we will give a high-level overview of many
  different packages.
- DevelopeRs of interactive packages are encouraged to come, to
  discuss the current state-of-the-art and future directions.
